In [1]:
import pandas as pd

In [2]:
jul_2022 = pd.read_csv('data/2022/jul2022.csv')
aug_2022 = pd.read_csv('data/2022/aug2022.csv')
sep_2022 = pd.read_csv('data/2022/sep2022.csv')
oct_2022 = pd.read_csv('data/2022/oct2022.csv')
nov_2022 = pd.read_csv('data/2022/nov2022.csv')
dec_2022 = pd.read_csv('data/2022/dec2022.csv')

C:\Users\radov\AppData\Local\Temp\ipykernel_6016\3005994886.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  jul_2022 = pd.read_csv('data/2022/jul2022.csv')
C:\Users\radov\AppData\Local\Temp\ipykernel_6016\3005994886.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  aug_2022 = pd.read_csv('data/2022/aug2022.csv')
C:\Users\radov\AppData\Local\Temp\ipykernel_6016\3005994886.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  sep_2022 = pd.read_csv('data/2022/sep2022.csv')
C:\Users\radov\AppData\Local\Temp\ipykernel_6016\3005994886.py:4: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  oct_2022 = pd.read_csv('data/2022/oct2022.csv')
C:\Users\radov\AppData\Local\Temp\ipykernel_6016\3005994886.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  nov_2022 = pd.read_csv('data/2022/nov2022.csv')
C:\Users\radov\AppData\Local\Temp\ipykernel_6016\3005994886.py:6: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  dec_2022 = pd.read_csv('data/2022/dec2022.csv')

In [3]:
combined_2022 = pd.concat([jul_2022, aug_2022, sep_2022, oct_2022, nov_2022, dec_2022], ignore_index=True)

In [4]:
combined_2022

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C09E4093905089BD,classic_bike,2022-07-23 11:34:57,2022-07-23 11:45:08,Melrose St & Broadway,4801.04,Myrtle Ave & Grove St,4816.05,40.697481,-73.935877,40.699050,-73.915160,member
1,374630DB5822C392,electric_bike,2022-07-29 18:19:08,2022-07-29 18:26:50,E 68 St & 3 Ave,6896.16,E 85 St & York Ave,7146.04,40.767128,-73.962246,40.775369,-73.948034,member
2,4F73CA25880A1215,electric_bike,2022-07-16 16:30:58,2022-07-16 17:39:18,W 37 St & 10 Ave,6611.02,Knickerbocker Ave & Cooper St,4582.05,40.756604,-73.997901,40.690810,-73.904480,member
3,ECD6EE19C0CC1D31,electric_bike,2022-07-17 17:35:57,2022-07-17 18:03:36,W 37 St & 10 Ave,6611.02,6 Ave & Broome St,5610.09,40.756604,-73.997901,40.724310,-74.004730,member
4,44D0987673B9997D,classic_bike,2022-07-11 07:56:29,2022-07-11 07:59:15,E 68 St & 3 Ave,6896.16,E 66 St & Madison Ave,6969.08,40.767128,-73.962246,40.768009,-73.968453,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10094031,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member
10094032,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member
10094033,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member
10094034,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member
10094035,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member

In [8]:
combined_2022 = combined_2022.drop(columns=['ride_id'])

combined_2022.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,classic_bike,2022-07-23 11:34:57,2022-07-23 11:45:08,Melrose St & Broadway,4801.04,Myrtle Ave & Grove St,4816.05,40.697481,-73.935877,40.699050,-73.915160,member
1,electric_bike,2022-07-29 18:19:08,2022-07-29 18:26:50,E 68 St & 3 Ave,6896.16,E 85 St & York Ave,7146.04,40.767128,-73.962246,40.775369,-73.948034,member
2,electric_bike,2022-07-16 16:30:58,2022-07-16 17:39:18,W 37 St & 10 Ave,6611.02,Knickerbocker Ave & Cooper St,4582.05,40.756604,-73.997901,40.690810,-73.904480,member
3,electric_bike,2022-07-17 17:35:57,2022-07-17 18:03:36,W 37 St & 10 Ave,6611.02,6 Ave & Broome St,5610.09,40.756604,-73.997901,40.724310,-74.004730,member
4,classic_bike,2022-07-11 07:56:29,2022-07-11 07:59:15,E 68 St & 3 Ave,6896.16,E 66 St & Madison Ave,6969.08,40.767128,-73.962246,40.768009,-73.968453,member

In [9]:
combined_2022 = combined_2022.rename(columns={'started_at': 'start_time', 'ended_at': 'end_time'})

combined_2022.head()

,rideable_type,start_time,end_time,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,classic_bike,2022-07-23 11:34:57,2022-07-23 11:45:08,Melrose St & Broadway,4801.04,Myrtle Ave & Grove St,4816.05,40.697481,-73.935877,40.699050,-73.915160,member
1,electric_bike,2022-07-29 18:19:08,2022-07-29 18:26:50,E 68 St & 3 Ave,6896.16,E 85 St & York Ave,7146.04,40.767128,-73.962246,40.775369,-73.948034,member
2,electric_bike,2022-07-16 16:30:58,2022-07-16 17:39:18,W 37 St & 10 Ave,6611.02,Knickerbocker Ave & Cooper St,4582.05,40.756604,-73.997901,40.690810,-73.904480,member
3,electric_bike,2022-07-17 17:35:57,2022-07-17 18:03:36,W 37 St & 10 Ave,6611.02,6 Ave & Broome St,5610.09,40.756604,-73.997901,40.724310,-74.004730,member
4,classic_bike,2022-07-11 07:56:29,2022-07-11 07:59:15,E 68 St & 3 Ave,6896.16,E 66 St & Madison Ave,6969.08,40.767128,-73.962246,40.768009,-73.968453,member

In [10]:
combined_2022.to_csv('data/2022/combined_2022.csv', index=False)